### ISSUE TITLE
nanoflann orders of magnitude slower when using large samples

### ISSUE THREAD

**Issue by Nelthirion** [jlblancoc/nanoflann#69] opened 2018-02-13 07:36 UTC
Hi

I'm using the [Vector_of_Vectors](https://github.com/jlblancoc/nanoflann/blob/master/examples/vector_of_vectors_example.cpp) example to find nearest neighbors to 128 dimensional float vectors.

When using `1e6` samples everything seems fast enough: Building the tree and building the index.

But When using `1e7` samples which is 10 times larger, the tree takes a LOT more time to build and also to index.

I did this example in Python/Numpy/cKdTree and it really wasn't this slow to build the tree and index.

Is my approach wrong?

```
#include <nanoflann.hpp>
using namespace nanoflann;

#include "KDTreeVectorOfVectorsAdaptor.h"

#include <ctime>
#include <cstdlib>
#include <iostream>

const int SAMPLES_DIM = 128;

typedef std::vector<std::vector<float>> my_vector_of_vectors_t;


void generateRandomPointCloud(my_vector_of_vectors_t& samples,
                              const size_t N = 1e7,
                              const size_t dim = 128,
                              const float max_range = 1.0)
{
	std::cout << "Generating " << N << " random points...";
	samples.resize(N);
	for (size_t i = 0; i < N; i++)
	{
		samples[i].resize(dim);
		for (size_t d = 0; d < dim; d++)
			samples[i][d] = max_range * (rand() % 1000) / (1000.0);
	}
	std::cout << "done\n";
}

void kdtree_demo(const size_t nSamples = 1e7, const size_t dim = 128)
{
	my_vector_of_vectors_t samples;

	const float max_range = 1.0;

	// Generate points:
	generateRandomPointCloud(samples, nSamples, dim, max_range);

	// Query point:
	std::vector<float> query_pt(dim);
	for (size_t d = 0; d < dim; d++)
		query_pt[d] = max_range * (rand() % 1000) / (1000.0);

	// construct a kd-tree index:
	// Dimensionality set at run-time (default: L2)
	// ------------------------------------------------------------
	std::cout << "Constructing Kd Tree" << std::endl;
	typedef KDTreeVectorOfVectorsAdaptor<my_vector_of_vectors_t, float> my_kd_tree_t;
	my_kd_tree_t mat_index(dim /*dim*/, samples, 20 /* max leaf */);

	std::cout << "Building Index" << std::endl;
	mat_index.index->buildIndex();

	std::cout << "Initializing Indexes" << std::endl;
	// do a knn search
	const size_t num_results = 3;
	std::vector<size_t> ret_indexes(num_results);
	std::vector<float> out_dists_sqr(num_results);

	std::cout << "Initializing Resultset" << std::endl;
	nanoflann::KNNResultSet<float> resultSet(num_results);
	resultSet.init(&ret_indexes[0], &out_dists_sqr[0]);

	std::cout << "Starting " << std::endl;
	mat_index.index->findNeighbors(resultSet, &query_pt[0], nanoflann::SearchParams(10));

	std::cout << "knnSearch(number or results=" << num_results << "): \n";
	for (size_t i = 0; i < num_results; i++)
		std::cout << "ret_index[" << i << "]=" << ret_indexes[i] << " out_dist_sqr=" << out_dists_sqr[i] << std::endl;
}

int main()
{
	// Randomize Seed
	srand(time(NULL));
	kdtree_demo(1e7 /* samples */, SAMPLES_DIM /* dim */);
}

```

**Comment by Nelthirion** [comment] 2018-02-13 07:41
And also when I looked inside the constructor for `mat_index` I saw that we have a call to `index->buildIndex();` so why do we have to explicitly call this again in the next line:

```
my_kd_tree_t   mat_index(dim /*dim*/, samples, 10 /* max leaf */ ); // This already calls `index->buildIndex()`
mat_index.index->buildIndex();
```

**Comment by jlblancoc** [comment] 2018-02-15 00:09
> But When using 1e7 samples which is 10 times larger, the tree takes a LOT more time to build and also to index.

No, I think you didn't do anything wrong. But you might have hit a performance limit related to the size of your L3 cache memory. 
However, I would **not** recommend the vector_of_vector container for very large datasets, since it involves `N` calls to the memory allocator (once per vector). Instead, use the Matrix adaptor or even better write your own wrapper to avoid data duplication, directly accessing to data in whatever form it's originally kept in your program. 

> And also when I looked inside the constructor for mat_index I saw that we 
> have a call to index->buildIndex(); so why do we have to explicitly call this again in the next line:

Good point. Please, feel free of opening a pull request to fix the code/example. I guess that keeping the call inside the ctor is the expected behavior by the user, so the second one is the one that needs to be removed.

**Comment by jlblancoc** [comment] 2018-02-15 00:10
PS: An efficient kind of Matrix for this case is **not** Eigen::MatrixXd, but a matrix with one dimension (e.g. number of cols) fixed in compile-time to 128 or whatever is the feature length.

**Closed** 2022-11-18 00:08 UTC
